import type { Listing } from './listings'

// Default values for fields not relevant to mock data
const mockDefaults = {
    bedsAboveGrade: null,
    bedsBelowGrade: null,
    bathsFull: null,
    bathsHalf: null,
    lotSizeDimensions: null,
    buildingType: null,
    storeys: null,
    constructionMaterial: null,
    foundation: null,
    roof: null,
    exteriorFeatures: null,
    flooring: null,
    interiorFeatures: null,
    appliances: null,
    basement: null,
    heating: null,
    heatingFuel: null,
    cooling: null,
    waterSource: null,
    sewer: null,
    parkingTotal: null,
    garageSpaces: null,
    parkingFeatures: null,
    taxAmount: null,
    taxYear: null,
    associationFee: null,
    associationFeeFrequency: null,
    rooms: [],
    roomsTotal: null,
    zoning: null,
    communityFeatures: null,
    poolFeatures: null,
    fencing: null,
    isRental: false,
    rentPrice: null,
    rentFrequency: null,
    latitude: null,
    longitude: null,
} satisfies Partial<Listing>

export const mockListings: Listing[] = [
    {
        ...mockDefaults,
        id: '405-myers-b30',
        mlsNumber: '405-MYERS-B30',
        address: {
            full: '405 MYERS Road Unit# B30, Cambridge, Ontario',
            streetNumber: '405',
            streetName: 'MYERS Road',
            unitNumber: 'B30',
            city: 'Cambridge',
            province: 'Ontario',
            postalCode: 'N1R 5A6',
            neighbourhood: null,
        },
        price: 2220,
        beds: 2,
        baths: 2,
        sqft: 920,
        lotSize: null,
        propertyType: 'Residential Leasing',
        yearBuilt: null,
        description: 'Modern 2-bedroom, 2-bathroom unit in a prime Cambridge location.',
        photos: ['/images/listing-placeholder.webp'],
        listDate: new Date().toISOString(),
        daysOnMarket: 1,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: 'https://www.realtor.ca/real-estate/27674251/405-myers-road-unit-b30-cambridge',
    },
    {
        ...mockDefaults,
        id: 'mock-1',
        mlsNumber: 'X12345678',
        address: {
            full: '142 Williamsburg Road, Kitchener, ON N2E 1W8',
            streetNumber: '142',
            streetName: 'Williamsburg Road',
            unitNumber: null,
            city: 'Kitchener',
            province: 'ON',
            postalCode: 'N2E 1W8',
            neighbourhood: 'Williamsburg',
        },
        price: 849000,
        beds: 4,
        baths: 3,
        sqft: 2100,
        lotSize: '40 x 110 ft',
        propertyType: 'Detached',
        yearBuilt: 2005,
        description: 'Beautiful family home in sought-after Williamsburg neighbourhood.',
        photos: ['/images/house-1.webp'],
        listDate: new Date(Date.now() - 3 * 86400000).toISOString(),
        daysOnMarket: 3,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        ...mockDefaults,
        id: 'mock-2',
        mlsNumber: 'X12345679',
        address: {
            full: '88 Bridgeport Road E, Waterloo, ON N2J 2K4',
            streetNumber: '88',
            streetName: 'Bridgeport Road E',
            unitNumber: null,
            city: 'Waterloo',
            province: 'ON',
            postalCode: 'N2J 2K4',
            neighbourhood: null,
        },
        price: 699000,
        beds: 3,
        baths: 2,
        sqft: 1650,
        lotSize: '35 x 100 ft',
        propertyType: 'Semi-Detached',
        yearBuilt: 1998,
        description: 'Tastefully updated semi in central Waterloo.',
        photos: ['/images/listing-placeholder.webp'],
        listDate: new Date(Date.now() - 1 * 86400000).toISOString(),
        daysOnMarket: 1,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        ...mockDefaults,
        id: 'mock-3',
        mlsNumber: 'X12345680',
        address: {
            full: '310 Lakeshore Road, Cambridge, ON N1R 5A6',
            streetNumber: '310',
            streetName: 'Lakeshore Road',
            unitNumber: null,
            city: 'Cambridge',
            province: 'ON',
            postalCode: 'N1R 5A6',
            neighbourhood: null,
        },
        price: 589000,
        beds: 3,
        baths: 1,
        sqft: 1200,
        lotSize: '50 x 130 ft',
        propertyType: 'Detached',
        yearBuilt: 1975,
        description: 'Solid brick bungalow on a generous lot.',
        photos: ['/images/listing-placeholder.webp'],
        listDate: new Date(Date.now() - 7 * 86400000).toISOString(),
        daysOnMarket: 7,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        ...mockDefaults,
        id: 'mock-4',
        mlsNumber: 'X12345681',
        address: {
            full: '45 Doon Village Road, Kitchener, ON N2P 1A4',
            streetNumber: '45',
            streetName: 'Doon Village Road',
            unitNumber: null,
            city: 'Kitchener',
            province: 'ON',
            postalCode: 'N2P 1A4',
            neighbourhood: 'Doon South',
        },
        price: 1150000,
        beds: 4,
        baths: 4,
        sqft: 3200,
        lotSize: '55 x 120 ft',
        propertyType: 'Detached',
        yearBuilt: 2010,
        description: 'Luxury custom home in prestigious Doon South.',
        photos: ['/images/listing-placeholder.webp'],
        listDate: new Date(Date.now() - 14 * 86400000).toISOString(),
        daysOnMarket: 14,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        ...mockDefaults,
        id: 'mock-5',
        mlsNumber: 'X12345682',
        address: {
            full: '12 Caroline Street N, Waterloo, ON N2L 2Y2',
            streetNumber: '12',
            streetName: 'Caroline Street N',
            unitNumber: '504',
            city: 'Waterloo',
            province: 'ON',
            postalCode: 'N2L 2Y2',
            neighbourhood: 'Uptown',
        },
        price: 450000,
        beds: 1,
        baths: 1,
        sqft: 750,
        lotSize: null,
        propertyType: 'Condo',
        yearBuilt: 2018,
        description: 'Modern 1-bedroom condo in prime Uptown Waterloo.',
        photos: ['/images/listing-placeholder.webp'],
        listDate: new Date(Date.now() - 2 * 86400000).toISOString(),
        daysOnMarket: 2,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
    {
        ...mockDefaults,
        id: 'mock-6',
        mlsNumber: 'X12345683',
        address: {
            full: '77 Forest Hill Drive, Kitchener, ON N2M 4G3',
            streetNumber: '77',
            streetName: 'Forest Hill Drive',
            unitNumber: null,
            city: 'Kitchener',
            province: 'ON',
            postalCode: 'N2M 4G3',
            neighbourhood: 'Forest Hill',
        },
        price: 725000,
        beds: 3,
        baths: 2,
        sqft: 1800,
        lotSize: '45 x 115 ft',
        propertyType: 'Detached',
        yearBuilt: 1982,
        description: 'Well-maintained split-level home in Forest Hill.',
        photos: ['/images/listing-placeholder.webp'],
        listDate: new Date(Date.now() - 5 * 86400000).toISOString(),
        daysOnMarket: 5,
        status: 'Active',
        virtualTour: null,
        listingBrokerage: 'RE/MAX Twin City Realty Inc.',
        realtorCaUrl: '#',
    },
]
